project:
  type: website
  output-dir: docs

website:
  title: "kyobin-blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://kyobin-koo.github.io/kyobin-blog/

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



